/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package szamolas_feladat;

/**
 *
 * @author Petra
 */
public class Szamolas_feladat extends javax.swing.JFrame {

    /**
     * Creates new form Szamolasos_feladat
     */
    public Szamolas_feladat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jMenuItem1 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlGyakorlas = new javax.swing.JPanel();
        lblFeladat = new javax.swing.JLabel();
        txtEredmeny = new javax.swing.JTextField();
        lblValasz = new javax.swing.JLabel();
        btnEllenorzes = new javax.swing.JButton();
        btnUj = new javax.swing.JButton();
        btnMegoldas = new javax.swing.JButton();
        pnlStatisztika = new javax.swing.JPanel();
        lblOsszKerdes = new javax.swing.JLabel();
        lblOsszProba = new javax.swing.JLabel();
        lblOsszeadKerdes = new javax.swing.JLabel();
        lblOsszeadProba = new javax.swing.JLabel();
        lblKivonasKerdes = new javax.swing.JLabel();
        lblKivonasProba = new javax.swing.JLabel();
        lblOsztasKerdes = new javax.swing.JLabel();
        lblOsztasProba = new javax.swing.JLabel();
        lblSzorzasKerdes = new javax.swing.JLabel();
        lblSzorzasProba = new javax.swing.JLabel();
        lblEredmeny = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFajlMegnyit = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        mnuFajlMent = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuFajlKilep = new javax.swing.JMenuItem();
        mnuMuveletek = new javax.swing.JMenu();
        mnuMuveletekOsszeadas = new javax.swing.JRadioButtonMenuItem();
        mnuMuveletekKivonas = new javax.swing.JRadioButtonMenuItem();
        mnuMuveletekOsztas = new javax.swing.JRadioButtonMenuItem();
        mnuMuveletekSzorzas = new javax.swing.JRadioButtonMenuItem();

        jLabel3.setText("jLabel3");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alapműveletek gyakorlása");

        pnlGyakorlas.setBorder(javax.swing.BorderFactory.createTitledBorder("Gyakorlás"));

        lblFeladat.setText("5 + 12 =");

        lblValasz.setText("Jó / Nem jó");

        btnEllenorzes.setText("Ellenőrzés");
        btnEllenorzes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEllenorzesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlGyakorlasLayout = new javax.swing.GroupLayout(pnlGyakorlas);
        pnlGyakorlas.setLayout(pnlGyakorlasLayout);
        pnlGyakorlasLayout.setHorizontalGroup(
            pnlGyakorlasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGyakorlasLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pnlGyakorlasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblValasz)
                    .addGroup(pnlGyakorlasLayout.createSequentialGroup()
                        .addComponent(lblFeladat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEredmeny, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEllenorzes)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        pnlGyakorlasLayout.setVerticalGroup(
            pnlGyakorlasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGyakorlasLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(pnlGyakorlasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFeladat)
                    .addComponent(txtEredmeny, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEllenorzes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblValasz)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btnUj.setText("Új feladat");
        btnUj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUjActionPerformed(evt);
            }
        });

        btnMegoldas.setText("Megoldás");
        btnMegoldas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMegoldasActionPerformed(evt);
            }
        });

        pnlStatisztika.setBorder(javax.swing.BorderFactory.createTitledBorder("Statisztika"));

        lblOsszKerdes.setText("Össz kérdések száma: 1");

        lblOsszProba.setText("Össz Próbálkozások száma: 1");

        lblOsszeadKerdes.setText("Összeadás: 1");

        lblOsszeadProba.setText("Összeadás: 1");

        lblKivonasKerdes.setText("Kivonás: 0");

        lblKivonasProba.setText("Kivonás: 0");

        lblOsztasKerdes.setText("Osztás: 0");

        lblOsztasProba.setText("Osztás: 0");

        lblSzorzasKerdes.setText("Szorzás: 0");

        lblSzorzasProba.setText("Szorzás: 0");

        lblEredmeny.setText("Eredmény: 0 %");

        javax.swing.GroupLayout pnlStatisztikaLayout = new javax.swing.GroupLayout(pnlStatisztika);
        pnlStatisztika.setLayout(pnlStatisztikaLayout);
        pnlStatisztikaLayout.setHorizontalGroup(
            pnlStatisztikaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStatisztikaLayout.createSequentialGroup()
                .addComponent(lblEredmeny)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStatisztikaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlStatisztikaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlStatisztikaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlStatisztikaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOsztasKerdes, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblKivonasKerdes, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSzorzasKerdes, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(152, 152, 152)
                        .addGroup(pnlStatisztikaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblKivonasProba, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblOsztasProba, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSzorzasProba, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlStatisztikaLayout.createSequentialGroup()
                        .addGroup(pnlStatisztikaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblOsszeadKerdes)
                            .addComponent(lblOsszKerdes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlStatisztikaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOsszProba, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblOsszeadProba, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(19, 19, 19))
        );
        pnlStatisztikaLayout.setVerticalGroup(
            pnlStatisztikaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStatisztikaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlStatisztikaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOsszKerdes)
                    .addComponent(lblOsszProba))
                .addGap(18, 18, 18)
                .addGroup(pnlStatisztikaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOsszeadKerdes)
                    .addComponent(lblOsszeadProba))
                .addGap(7, 7, 7)
                .addGroup(pnlStatisztikaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKivonasKerdes)
                    .addComponent(lblKivonasProba))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlStatisztikaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOsztasKerdes)
                    .addComponent(lblOsztasProba))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlStatisztikaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSzorzasKerdes)
                    .addComponent(lblSzorzasProba))
                .addGap(38, 38, 38)
                .addComponent(lblEredmeny)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mnuFajlMegnyit.setText("Fájl");

        jMenuItem2.setText("Megnyit");
        mnuFajlMegnyit.add(jMenuItem2);

        mnuFajlMent.setText("Ment");
        mnuFajlMegnyit.add(mnuFajlMent);
        mnuFajlMegnyit.add(jSeparator1);

        mnuFajlKilep.setText("Kilép");
        mnuFajlMegnyit.add(mnuFajlKilep);

        jMenuBar1.add(mnuFajlMegnyit);

        mnuMuveletek.setText("Műveletek");

        buttonGroup1.add(mnuMuveletekOsszeadas);
        mnuMuveletekOsszeadas.setText("Összeadás");
        mnuMuveletek.add(mnuMuveletekOsszeadas);

        buttonGroup1.add(mnuMuveletekKivonas);
        mnuMuveletekKivonas.setText("Kivonás");
        mnuMuveletek.add(mnuMuveletekKivonas);

        buttonGroup1.add(mnuMuveletekOsztas);
        mnuMuveletekOsztas.setText("Osztás");
        mnuMuveletekOsztas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMuveletValasztas(evt);
            }
        });
        mnuMuveletek.add(mnuMuveletekOsztas);

        buttonGroup1.add(mnuMuveletekSzorzas);
        mnuMuveletekSzorzas.setText("Szorzás");
        mnuMuveletek.add(mnuMuveletekSzorzas);

        jMenuBar1.add(mnuMuveletek);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlStatisztika, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlGyakorlas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMegoldas)
                            .addComponent(btnUj))
                        .addGap(0, 5, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(pnlGyakorlas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnUj)
                        .addGap(40, 40, 40)
                        .addComponent(btnMegoldas)
                        .addGap(35, 35, 35)))
                .addComponent(pnlStatisztika, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuMuveletValasztas(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMuveletValasztas
        if (mnuMuveletekOsztas.isSelected()) {
            lblFeladat.setText("20 / 5 = ");
        }
    }//GEN-LAST:event_mnuMuveletValasztas

    private void btnEllenorzesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEllenorzesActionPerformed
        if (txtEredmeny.getText().equals("4")) {
            lblValasz.setText("4 jó!");
            txtEredmeny.setText("");
            btnEllenorzes.setEnabled(false);
        }else if (txtEredmeny.getText().equals("")) {
            lblValasz.setText("Nincs érték!");
        }
        else{
            lblValasz.setText(txtEredmeny.getText()+" nem jó!");
            txtEredmeny.setText("");
        }
    }//GEN-LAST:event_btnEllenorzesActionPerformed

    private void btnMegoldasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMegoldasActionPerformed
        lblValasz.setText("Jó / Nem jó");
        txtEredmeny.setText("4");
        btnEllenorzes.setEnabled(false);
    }//GEN-LAST:event_btnMegoldasActionPerformed

    private void btnUjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUjActionPerformed
        lblFeladat.setText("20 / 5 = ");
        txtEredmeny.setText("");
        btnEllenorzes.setEnabled(true);
    }//GEN-LAST:event_btnUjActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Szamolas_feladat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Szamolas_feladat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Szamolas_feladat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Szamolas_feladat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Szamolas_feladat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEllenorzes;
    private javax.swing.JButton btnMegoldas;
    private javax.swing.JButton btnUj;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblEredmeny;
    private javax.swing.JLabel lblFeladat;
    private javax.swing.JLabel lblKivonasKerdes;
    private javax.swing.JLabel lblKivonasProba;
    private javax.swing.JLabel lblOsszKerdes;
    private javax.swing.JLabel lblOsszProba;
    private javax.swing.JLabel lblOsszeadKerdes;
    private javax.swing.JLabel lblOsszeadProba;
    private javax.swing.JLabel lblOsztasKerdes;
    private javax.swing.JLabel lblOsztasProba;
    private javax.swing.JLabel lblSzorzasKerdes;
    private javax.swing.JLabel lblSzorzasProba;
    private javax.swing.JLabel lblValasz;
    private javax.swing.JMenuItem mnuFajlKilep;
    private javax.swing.JMenu mnuFajlMegnyit;
    private javax.swing.JMenuItem mnuFajlMent;
    private javax.swing.JMenu mnuMuveletek;
    private javax.swing.JRadioButtonMenuItem mnuMuveletekKivonas;
    private javax.swing.JRadioButtonMenuItem mnuMuveletekOsszeadas;
    private javax.swing.JRadioButtonMenuItem mnuMuveletekOsztas;
    private javax.swing.JRadioButtonMenuItem mnuMuveletekSzorzas;
    private javax.swing.JPanel pnlGyakorlas;
    private javax.swing.JPanel pnlStatisztika;
    private javax.swing.JTextField txtEredmeny;
    // End of variables declaration//GEN-END:variables
}
